language: node_js

node_js:
  - 6.10.2

services:
  - postgresql

before_script:
  - psql -c 'drop database if exists okdocs_test;' -U postgres
  - psql -c 'create database okdocs_test;' -U postgres

script: 
  - npm test
after_success:
  - npm run report-coverage
