
const actionTypes = {
  // Create User
  WILL_CREATE_USER: 'WILL_CREATE_USER',
  CREATE_USER: 'CREATE_USER',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',

  // Create User
  SIGNIN_USER: 'SIGNIN_USER',
  SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
  SIGNIN_USER_FAILURE: 'SIGNIN_USER_FAILURE',
  SET_USER_DETAILS: 'SET_USER_DETAILS',
};

export default actionTypes;
