const initialState = {
  documentReducer: {
    count: 0,
    documents: [],
    userDocuments: [],
    deletingDocument: false,
    fetchingDocuments: false,
  },
  userReducers: {
    users: [],
    user: {},
    updatingUser: false,
    fetchingUsers: false,
    fetchingUser: false,
    authenticated: false,
    signingIn: false,
    createdUser: false,
    count: 0,
  },
  users: [],
  user: {},
  updatingUser: false,
  fetchingUsers: false,
  fetchingUser: false,
  authenticated: false,
  signingIn: false,
  createdUser: false,
  count: 0,
  documents: [],
  userDocuments: [],
  deletingDocument: false,
  fetchingDocuments: false,
};

export default initialState;
